# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application
on:
  push:
    branches:
    - master

default_language_version:
  python: python3.8

default_stages: [commit]

exclude: '(infra|test)/.*'

repos:
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
        args:
          - --py39-plus

  - repo: https://github.com/python/black
    rev: 22.12.0
    hooks:
      - id: black
        name: black
      - id: black-jupyter
        name: black-jupyter

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.219'
    hooks:
      - id: ruff
        args: [ "--force-exclude" ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: debug-statements
      - id: requirements-txt-fixer # order requirements alphabetically
      - id: check-ast # Simply check whether the files parse as valid python
      - id: check-case-conflict # Check for files that would conflict in case-insensitive filesystems
      - id: check-builtin-literals # Require literal syntax when initializing empty or zero Python builtin types
      - id: check-docstring-first # Check a common error of defining a docstring after code
      - id: check-merge-conflict # Check for files that contain merge conflict strings
      - id: check-yaml # Check yaml files
        args: ["--unsafe"]
      - id: end-of-file-fixer # Ensure that a file is either empty, or ends with one newline
      - id: mixed-line-ending # Replace or checks mixed line ending
      - id: trailing-whitespace # This hook trims trailing whitespace

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    - id: mypy
      args: [--config-file=mypy.ini]
      additional_dependencies:
        - hydra-core==1.3.2
        - neptune==1.0.2
        - numpy==1.22.4
        - pandas==1.5.2
        - pydantic==1.10.2
        - pytest-mock==3.10.0
        - pytest==7.2.0
        - s3fs==2023.3.0
        - types-PyYAML
        - types-setuptools

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [TRAIN, ci, refactor, docs, notebook]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
      - id: pyupgrade
        args:
          - --py38-plus
